= Cheatsheets

[[MailAttachment]]
== MailAttachment

++++
 Represent a mail attachment that can be used in a MailMessage.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[contentType]]`contentType`|`String`|
+++
get the Content-Type
+++
|[[data]]`data`|`Buffer`|
+++
get the data
+++
|[[description]]`description`|`String`|
+++
get the description field
+++
|[[disposition]]`disposition`|`String`|
+++
get the disposition field
+++
|[[name]]`name`|`String`|
+++
get the name
+++
|===

[[MailConfig]]
== MailConfig

++++
 represents the configuration of a mail service with mail server hostname,
 port, security options, login options and login/password
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[allowRcptErrors]]`allowRcptErrors`|`Boolean`|
+++
get if sending allows rcpt errors (default is false)
<p>
 if true, the mail will be sent to the recipients that the server accepted, if any
<p>
+++
|[[authMethods]]`authMethods`|`String`|
+++
get string of allowed auth methods, if set only these methods will be used
 if the server supports them. If null or empty all supported methods may be
 used
+++
|[[hostname]]`hostname`|`String`|
+++
get the hostname of the mailserver
+++
|[[keepAlive]]`keepAlive`|`Boolean`|
+++
get if connection pool is enabled
 default is true
<p>
 if the connection pooling is disabled, the max number of sockets is enforced nevertheless
<p>
+++
|[[keyStore]]`keyStore`|`String`|
+++
get the key store filename to be used when opening SMTP connections
+++
|[[keyStorePassword]]`keyStorePassword`|`String`|
+++
get the key store password to be used when opening SMTP connections
+++
|[[login]]`login`|`link:enums.html#LoginOption[LoginOption]`|
+++
get login options
+++
|[[maxPoolSize]]`maxPoolSize`|`Number (int)`|
+++
get the max allowed number of open connections to the mailserver
 if not set the default is 10
+++
|[[ownHostname]]`ownHostname`|`String`|
+++
get the hostname to be used for HELO/EHLO and the Message-ID
+++
|[[password]]`password`|`String`|
+++
get password
+++
|[[port]]`port`|`Number (int)`|
+++
get the port of the mailserver
+++
|[[ssl]]`ssl`|`Boolean`|
+++
get whether ssl is used on connect
+++
|[[starttls]]`starttls`|`link:enums.html#StartTLSOptions[StartTLSOptions]`|
+++
get security (TLS) options
+++
|[[trustAll]]`trustAll`|`Boolean`|
+++
get whether to trust all certificates on ssl connect
+++
|[[username]]`username`|`String`|
+++
get username
+++
|===

[[MailMessage]]
== MailMessage

++++
 represent a mail message that can be sent via the MailClient
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[attachment]]`attachment`|`Array of link:dataobjects.html#MailAttachment[MailAttachment]`|
+++
get the list of attachments of this mail
+++
|[[bcc]]`bcc`|`Array of String`|
+++
get list of bcc addresses
+++
|[[bounceAddress]]`bounceAddress`|`String`|
+++
get bounce address of this mail
+++
|[[cc]]`cc`|`Array of String`|
+++
get list of cc addresses
+++
|[[fixedHeaders]]`fixedHeaders`|`Boolean`|
+++
get whether our own headers should be the only headers added to the message
+++
|[[from]]`from`|`String`|
+++
get from address of this mail
+++
|[[html]]`html`|`String`|
+++
get the html text of this mail
+++
|[[subject]]`subject`|`String`|
+++
get the subject of this mail
+++
|[[text]]`text`|`String`|
+++
get the plain text of this mail
+++
|[[to]]`to`|`Array of String`|
+++
get list of to addresses
+++
|===

[[MailResult]]
== MailResult

++++
 Represent the result of the sendMail operation
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[messageID]]`messageID`|`String`|
+++
@return the messageID
+++
|[[recipients]]`recipients`|`Array of String`|
+++
@return the recipients
+++
|===

