== MailMessage

++++
 represent a mail message that can be sent via the MailClient
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[attachment]]`attachment`
|`link:MailAttachment.html[MailAttachment]`
|+++
set a single attachment of this mail the result of getAttachment when using
 this method returns an unmodifiable list, if you want to be able to add
 attachments later, please use
 <code>setAttachment(new ArrayList<MailAttachment>())</code> instead+++

|[[bcc]]`bcc`
|`String`
|+++
helper method for single recipient+++

|[[bounceAddress]]`bounceAddress`
|`String`
|+++
set bounce address of this mail+++

|[[cc]]`cc`
|`String`
|+++
helper method for single recipient+++

|[[fixedHeaders]]`fixedHeaders`
|`Boolean`
|+++
set whether our own headers should be the only headers added to the message+++

|[[from]]`from`
|`String`
|+++
set from address of this mail+++

|[[html]]`html`
|`String`
|+++
set the html text of this mail+++

|[[subject]]`subject`
|`String`
|+++
set the subject of this mail+++

|[[text]]`text`
|`String`
|+++
set the plain text of this mail+++

|[[to]]`to`
|`String`
|+++
helper method for single recipient+++
|===
