== MailConfig

++++
 represents the configuration of a mail service with mail server hostname,
 port, security options, login options and login/password
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description

|[[allowRcptErrors]]`allowRcptErrors`
|`Boolean`
|+++
set if sending allows rcpt errors+++

|[[authMethods]]`authMethods`
|`String`
|+++
set string of allowed auth methods.
 if set only these methods will be used
 if the server supports them. If null or empty all supported methods may be
 used+++

|[[hostname]]`hostname`
|`String`
|+++
Set the hostname of the smtp server.+++

|[[keepAlive]]`keepAlive`
|`Boolean`
|+++
set if connection pool is enabled
 default is true
<p>
 if the connection pooling is disabled, the max number of sockets is enforced nevertheless
<p>+++

|[[keyStore]]`keyStore`
|`String`
|+++
get the key store filename to be used when opening SMTP connections
 <p>
 if not set, an options object will be created based on other settings (ssl
 and trustAll)+++

|[[keyStorePassword]]`keyStorePassword`
|`String`
|+++
get the key store password to be used when opening SMTP connections+++

|[[login]]`login`
|`Enum`
|+++
Set the login mode for the connection.
 <p>
 Either DISABLED, OPTIONAL or REQUIRED+++

|[[maxPoolSize]]`maxPoolSize`
|`Number (int)`
|+++
set the max allowed number of open connections to the mail server
 if not set the default is 10+++

|[[ownHostname]]`ownHostname`
|`String`
|+++
set the hostname to be used for HELO/EHLO and the Message-ID+++

|[[password]]`password`
|`String`
|+++
Set the password for the login.+++

|[[port]]`port`
|`Number (int)`
|+++
Set the port of the smtp server.+++

|[[ssl]]`ssl`
|`Boolean`
|+++
Set the sslOnConnect mode for the connection.+++

|[[starttls]]`starttls`
|`Enum`
|+++
Set the tls security mode for the connection.
 <p>
 Either NONE, OPTIONAL or REQUIRED+++

|[[trustAll]]`trustAll`
|`Boolean`
|+++
set whether to trust all certificates on ssl connect the option is also
 applied to STARTTLS operation+++

|[[username]]`username`
|`String`
|+++
Set the username for the login.+++
|===
